# Generated by Django 4.2.7 on 2024-02-29 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specs', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('htype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headphones', to='store.headphonetype')),
            ],
        ),
    ]
