# Generated by Django 4.2.7 on 2024-02-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_headphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='headphone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images'),
        ),
    ]
