# Generated by Django 4.2.7 on 2024-03-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_headphone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headphone',
            name='htype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.headphonetype'),
        ),
    ]
