# Generated by Django 4.2.7 on 2024-10-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_headphone_htype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headphone',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='HeadphoneType',
            new_name='ProductType',
        ),
    ]
